### PR TITLE
Add simple pip install, newick dependency and fix minimal example imports

### PR DESCRIPTION
**Pull request by scottgigante**
Hi! Thanks for your work on PROSSTT. I've made a couple of changes which I think improve the setup and tutorial experience.

### CODE REVIEW

**Comment by scottgigante** [comment]
I've also replaced the `sys.exit` in simulation.py with a `raise ValueError` - it's not very friendly to quit my python interpreter because I did something wrong :)

**Comment by scottgigante** [comment]
I've also removed the statement about python2 support - https://github.com/soedinglab/prosstt/blob/27c2796d543d94756319a257bf785bc0dfa00799/prosstt/simulation.py#L111 is one example of where Python2 will silently give the wrong results, as Python2 has the following behaviour:
```
>>> steps = 5
>>> 2 / steps
0
```

**Comment by scottgigante** [comment]
I've added another change: `tree.Tree.simulate_lineage` corrected the genes, not the modules, to the parent - the modules should be corrected instead so they reflect the true gene programs.

**Comment by galicae** [comment]
Thanks for the suggestions, Scott! Will look into that ASAP and let you know.

**Comment by galicae** [comment]
Ok, back from vacation and on a real computer again :smile: Thanks for catching these!

**Comment by scottgigante** [comment]
You're welcome! 😄

**Pull request merged**
